---
layout: cv
title: Branislav Bogosavac's CV
---
# Branislav Bogosavac
Software Developer

<div id="webaddress">
<a href="branislavbogosavac@linkedin.com">branislavbogosavac@linkedin.com</a>

</div>


## Currently

Working as an intern for Leavitt Software Solutions

### Specialized in

Python, C, C++, C#, HTML, CSS, JS, Kotlin, MySQL

### Research interests

Front-end deveolpment, machine learning applications

## Projects

### Software Development

- **Inventory Management System**
  - Developed a Python-based inventory management system for small businesses, facilitating real-time tracking of stock levels and automating reorder processes.
- **E-commerce Website**
  - Led the development of a responsive e-commerce website using HTML, CSS, and JavaScript, resulting in a 20% increase in online sales within the first quarter of launch.

## Education

`2013-2017`
__Belgrade Gymnasium - Belgrade, Serbia__

`2021 - now`
__Brigham Young University - Idaho - Rexburg, Idaho__


## Languages Spoken

English, Serbian, Russian, German, Ancient Greek

## Work Experience

`2022 - Present`
__Software Developer Intern__, Leavitt Software Solutions

- Collaborate with cross-functional teams to develop and maintain software solutions for client projects.
- Participate in Agile development processes, including sprint planning, daily stand-ups, and retrospectives.
- Contribute to code reviews and provide constructive feedback to improve code quality and maintainability.


### Footer

Last updated: May 2024