---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Branislav Bogosavac"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


### Elevator pitch

_TODO:paste your elevator pitch here_
_REMOVE ME: ELEVATOR PITCH IS A SHORT (3-5 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._

The project explores the relationship between the size of the engine and the highway fuel efficiency. By examinig a dataset of various car models, we discover a notable correlation between the two. Larger engine sizes tend to result in lower highway miles per gallon, and smaller engine sizes tend to result in higher highway miles per gallon. 

### QUESTION|TASK 1

__TODO:COPY PASTE QUESTION|TASK 1 FROM THE PROJECT HERE__

1.Finish the readings, setup, and be prepared with any questions to get your environment working smoothly (class for on-campus and Slack for online)

I have finished the readings and setup.


### QUESTION|TASK 2

__TODO: COPY PASTE QUESTION|TASK 2 FROM THE PROJECT HERE__

2.In VS Code, create the example chart from section 3.2.2 of the textbook. (Note: you will be using Plotly Express to display the chart instead of Altair which is used in the book)

_TODO: type your results and analysis here_

From the following chart we can see the relation between the "hwy" and "displ." "hwy" stands for highway miles per gallon (mpg), which is a measure of fuel efficiency for vehicles when driven on highways. "displ" stands for engine displacement, which is the total volume of all the cylinders in a nengine. Engine displacement is an important factor in determining the power and performance characteristics of an engine. 
From the analysis of the data chart, we see the trend the larger the engine- smaller the fuel efficiency, and smaller the engine- better the fuel efficiency. 


```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here

import pandas as pd
import plotly.express as px

mpg = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv")

chart = px.scatter(mpg, x='displ', y='hwy')  

chart.show()

```


### QUESTION|TASK 3

__TODO: COPY PASTE QUESTION|TASK 3 FROM THE PROJECT HERE__

3.Your final report should also include the table created from the following (assuming you have mpg from question 2)


_TODO: type your results and analysis here_

From the following table we see the summary of four of the properties of the dataset we are working with. It displays the first five data objects, specifying the manifacturer, model, year and the highway miles per galon for each vehicle. 

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here
(mpg
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
)

```
